
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 24 00:04:31 CST 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Signo_AdmiracionAbre = 5;
  public static final int Signo_PreguntaAbre = 7;
  public static final int Verbo = 12;
  public static final int Entero = 26;
  public static final int Signo_Punto = 2;
  public static final int Signo_Guion = 9;
  public static final int Preposicion = 17;
  public static final int Flotante = 24;
  public static final int Identificador = 22;
  public static final int Articulo = 18;
  public static final int Sustantivo = 15;
  public static final int EOF = 0;
  public static final int Negacion = 20;
  public static final int Ropa = 10;
  public static final int Exponencial = 23;
  public static final int error = 1;
  public static final int Real = 25;
  public static final int Signo_PuntoComa = 4;
  public static final int Pronombre = 13;
  public static final int Literal = 14;
  public static final int Conjuncion = 19;
  public static final int Signo_AdmiracionCierra = 6;
  public static final int Nombre_Propio = 21;
  public static final int Adverbio = 11;
  public static final int Signo_PreguntaCierra = 8;
  public static final int Signo_Coma = 3;
  public static final int Adjetivo = 16;
}

